transactions = [
    ["2026-09-01", "A101", "Laptop", 2, 75000],
    ["2026-09-02", "A102", "Mouse", 10, 1200],
    ["2026-09-03", "A101", "Laptop", 1, 75000],
    ["2026-09-04", "A103", "Keyboard", 5, 2500],
    ["2026-09-05", "A102", "Mouse", 8, 1200],
    ["2026-09-06", "A104", "Monitor", 10, 15000],  
    ["2026-09-07", "A105", "Printer", 2, 18000],
    ["2026-09-08", "A101", "Laptop", 1, 75000],
    ["2026-09-09", "A106", "Headphones", 6, 3500],
    ["2026-09-10", "A103", "Keyboard", 4, 2500],
    ["2026-09-11", "A107", "Webcam", 5, 4000],
    ["2026-09-12", "A102", "Mouse", 12, 1200],
    ["2026-09-13", "A108", "Tablet", 2, 30000],
    ["2026-09-14", "A109", "SSD", 7, 6500],
    ["2026-09-15", "A110", "Router", 3, 5000],
    ["2026-09-16", "A104", "Monitor", 10, 15000], 
    ["2026-09-17", "A111", "Graphics Card", 1, 55000],
    ["2026-09-18", "A105", "Printer", 1, 18000],
    ["2026-09-19", "A112", "USB Drive", 20, 800],
    ["2026-09-20", "A113", "Desk Chair", 2, 12000]
]
#1. Product Sales Analysis
# Generate a product-wise sales report containing:
# Product name
# Total quantity sold
# Total revenue generated
# For this assessment:
# Revenue = Quantity Sold × Unit Price
# Consider all transactions provided in the input data.

Total_quantity_sold={}
for date,id,product,quantity,price in transactions:
    revenue=quantity*price
    if product not in Total_quantity_sold:
        Total_quantity_sold[product]=quantity
    else:
        Total_quantity_sold[product]+=quantity

print("----Total Qunatity Sold----")
print(Total_quantity_sold)

print("---Total Revenue Generated----")

total_revenue={}
for date,id,product,quantity,price in transactions:
    revenue=quantity*price
    if product not in total_revenue:
        total_revenue[product]=revenue
    else:
        total_revenue[product]+=revenue
print(total_revenue)



#2. Product Ranking
# Display all products in the following order:
# Products with higher total revenue should appear first.
# If two products have the same total revenue, the product with higher total quantity sold should appear first.
# If both revenue and quantity are the same, order the products alphabetically by product name.


print("----product Ranking----")
product_ranking={}
sorted_revenue=[]
for i,j in total_revenue.items():
    sorted_revenue.append(j)
sorted_revenue.sort(reverse=True)
for i in sorted_revenue:
    for product,revenue in total_revenue.items():
        if i==revenue and product not in product_ranking.keys():
            product_ranking[product]=i
product_ranking_alphabetically={}
for i,j in product_ranking.items():
    for k,l in product_ranking.items():
        if j==l:
            if i>k:
                product_ranking_alphabetically[k]=l
            else:
                product_ranking_alphabetically[i]=j
        else:
            product_ranking_alphabetically[i]=j
print(product_ranking_alphabetically)

# 3. Top-Selling Product
# Identify the top-selling product based on total quantity sold.
# Also display:
# Product name
# Total quantity sold
# Note: Top-selling product is determined by quantity, not revenue.

print("----Top Selling Product----")
top_selling_product=""
total_quantity_sold=0
max_qunatity=[]
for product,quantity in Total_quantity_sold.items():
    max_qunatity.append(quantity)
max_qunatity.sort(reverse=True)
for product,quantity in Total_quantity_sold.items():
    if quantity==max_qunatity[0]:
        top_selling_product=product
        total_quantity_sold=quantity
print(f'top_selling_product: {top_selling_product}')
print(f'total_quantity_sold: {total_quantity_sold}')

# 4. Highest-Revenue Product
# Identify the product that generated the highest total revenue.
# Display:
# Product name
# Total quantity sold
# Total revenue

print("----Highest Revenue Product----")
product_name=""
quantity_sold=0
highest_revenue_value=0
for product,revenue in product_ranking.items():
    product_name=product
    highest_revenue_value=revenue
    break
for product,quantity in Total_quantity_sold.items():
    if product==product_name:
        quantity_sold=quantity
        break

print(f'product_name: {product_name}')
print(f'quantity_sold: {quantity_sold}')
print(f'highest_revenue_value:{highest_revenue_value}')

# 5. Customer Sales Analysis
# Using the Customer ID available in each transaction, calculate the total purchase value for each customer.
# For each customer:
# Customer Purchase Value = Sum of revenue generated by that customer
# Display the top 3 customers based on their total purchase value.
# For example:
print("--Customer sales Analysis----")
customer_sales={}
for date,id,product,qunatity,price in transactions:
    revenue=quantity*price
    if id not in customer_sales:
        customer_sales[id]=revenue
    else:
        customer_sales[id]+=revenue
top_purchase=[]
for id,revenue in customer_sales.items():
    top_purchase.append(revenue)
top_purchase.sort(reverse=True)
top_purchase_customers={}
for i in top_purchase:
    for id,revenue in customer_sales.items():
        if i==revenue:
            top_purchase_customers[id]=revenue
rank=1
for id,revenue in top_purchase_customers.items():
    if rank<=3:
        print(f'Rank:{rank}, CustomerID:{id}, purchase_value:{revenue}')
        rank+=1  

# 6. Highest-Revenue Day
# Identify the date on which the business generated the highest total revenue.
# Display:
# Date
# Total revenue generated on that date
# If more than one date has the same highest revenue, display all such dates.

print("----Highest-Revenue Day----")
datewise_revenue={}
for date,id,product,quantity,price in transactions:
    revenue=quantity*price
    datewise_revenue[date]=revenue
date_revenue=[]
for date,revenue in datewise_revenue.items():
    date_revenue.append(revenue)
date_revenue.sort(reverse=True)
Date=[]
Revenue=[]
for date,revenue in datewise_revenue.items():
    if date_revenue[0]==revenue:
        Date.append(date)
        Revenue.append(revenue)
print(f'Date: {Date}')
print(f'Revenue: {Revenue}')

# 7. Overall Sales Summary
# Display the following overall information:
# Total number of transactions
# Total quantity of products sold
# Total revenue generated
# Number of unique products
# Number of unique customers

print("--Over All Sales Summary--")

total_number_of_transactions=0
total_quantity_of_products_sold=0
total_revenue_generated=0
number_of_unique_products=[]
number_of_unique_customers=[]
for date,id,product,qunatity,price in transactions:
    revenue=qunatity*price
    total_number_of_transactions+=1
    total_quantity_of_products_sold+=qunatity
    total_revenue_generated+=revenue
    if product not in number_of_unique_products:
        number_of_unique_products.append(product)
    if id not in number_of_unique_customers:
        number_of_unique_customers.append(id)
print(f'total_number_of_transactions:{total_number_of_transactions}')
print(f'total_quantity_of_products_sold:{total_quantity_of_products_sold}')
print(f'total_revenue_generated:{total_revenue_generated}')
print(f'number_of_unique_products:{len(number_of_unique_products)}')
print(f'number_of_unique_customers:{len(number_of_unique_customers)}')